name: Sanjula's Latest Youtube Videos workflow
on:
  workflow_dispatch: # Run workflow manually (without waiting for the cron to be called), through the Github Actions Workflow page directly
jobs:
  update-readme-with-youtube:
    name: Update this repo's README with Sanjula's latest Youtube videos
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: "https://youtube.com/feeds/videos.xml?channel_id=UC2emqq1KtzjMx6niZOgKoaA"